### ISSUE TITLE
telegram upload not working 

### ISSUE THREAD

**Issue by Pratyay360** [nikhilbadyal/docker-py-revanced#14]
![image](https://user-images.githubusercontent.com/61408566/192117845-ce0e4355-c5b4-4099-b149-77bb9805345b.png)
am i missing some apis op please help going arround

**Comment by nikhilbadyal** [comment]
What do you mean by not working? Does it throws some error or what?

**Comment by Pratyay360** [comment]
![image](https://user-images.githubusercontent.com/61408566/193411049-09c9bf6f-1d34-4735-a94c-fd20b6cbbc1a.png)

**Comment by Pratyay360** [comment]
file upload to telegram not working

**Comment by Pratyay360** [comment]
what is the difference between these two "TG_API_ID",  "TELEGRAM_API_ID"  
![image](https://user-images.githubusercontent.com/61408566/193411369-dccc6fc0-7f4c-4e92-af2e-cb9e4430bb32.png)

**Comment by nikhilbadyal** [comment]
You can get API_ID and API_HASH [here](https://my.telegram.org/apps). Also, there was a typo in action. I have updated it. So this should work now. But I would suggest not to use this as the underneath library is buggy. It takes almost an hour to upload all 5-6 apps.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/59223300/193412434-81e5a6b2-1deb-4c66-84ed-00daafe67fa6.png">

**Comment by Pratyay360** [comment]
thanks for replying, btw what is the difference between TG_API_ID, TELEGRAM_API_ID

**Comment by nikhilbadyal** [comment]
What was just a typo. Both are the same. It looks like this after fixing it.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/59223300/193412711-54a4ceb7-2073-4cb4-afd7-3af96822c408.png">

**Comment by nikhilbadyal** [comment]
Keeping it open for now. In case anyone wants to contribute, to the telegram upload script.

**Comment by Pratyay360** [comment]
still unable to configure it's skipping the job 
![image](https://user-images.githubusercontent.com/61408566/193447984-5789ddfb-a633-44f0-8b0c-e8bc62e11126.png)
my api names 
![image](https://user-images.githubusercontent.com/61408566/193448003-fe0e27b8-0e9d-4dec-85c4-c13ed8108f88.png)
i have generated telegram api from [link](https://my.telegram.org/apps).

**Comment by nikhilbadyal** [comment]
Click on re-run failed job and select `debug` option and share the logs here.

**Comment by Pratyay360** [comment]
https://pipelines.actions.githubusercontent.com/serviceHosts/338a003b-18c5-4960-bd08-39a228c03de6/_apis/pipelines/1/runs/57/signedlogcontent/2?urlExpires=2022-10-02T10%3A12%3A45.9595636Z&urlSigningMethod=HMACV1&urlSignature=78Oi0ELAbAtYeqefSQfzOkAoXN4w55PU8hmJGhl70WQ%3D

**Comment by nikhilbadyal** [comment]
As seen from the logs 
<img width="715" alt="image" src="https://user-images.githubusercontent.com/59223300/193449016-b9be81b1-faeb-4087-9145-114aaf867096.png">

this `HAVE_TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID != '' }}` this check is failing which mean API_ID is empty in your secrets. 
Can you recheck the GitHub secret again?

**Comment by Pratyay360** [comment]
![image](https://user-images.githubusercontent.com/61408566/193449542-7445cd10-e9ce-4b75-833b-34244330eb63.png)
[logs](https://pipelines.actions.githubusercontent.com/serviceHosts/338a003b-18c5-4960-bd08-39a228c03de6/_apis/pipelines/1/runs/60/signedlogcontent/2?urlExpires=2022-10-02T10%3A29%3A58.5253513Z&urlSigningMethod=HMACV1&urlSignature=rPELuTzuWlDU0HcoEuLFb2fIeOqCB0xLTluEBSUVOYw%3D)

**Comment by nikhilbadyal** [comment]
Share debug run. So that i can look into it. Also the link says expired.

**Comment by Pratyay360** [comment]
![image](https://user-images.githubusercontent.com/61408566/193449642-6d1d4cdf-5852-42a8-a2b0-00b43af7013e.png)

[logs_60.zip](https://github.com/nikhilbadyal/docker-py-revanced/files/9692253/logs_60.zip)

**Comment by nikhilbadyal** [comment]
You can see the last line of the exception. Your **API_ID** and **API_HASH** _combination_ is invalid. Regenerate (if it's allowed) or enter details properly.

**Comment by Pratyay360** [comment]
thanks it's working, can i contribute by adding the instructions on how to configure the telegram upload action

**Comment by nikhilbadyal** [comment]
Sure, would love any kind of contribution. 💪
